// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ocyucupwnmxrpjwhnjmv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9jeXVjdXB3bm14cnBqd2huam12Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1NDI0MDcsImV4cCI6MjA1ODExODQwN30.xA8sOpVrfVc8afhAhzvMTtxP9i1JrWomkdE1C_AFnNU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);